//
// CountryAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class CountryAPI: APIBase {

    public class func mapValuesToQueryItems(values: [String:Any?]) -> [URLQueryItem] {
        return values
            .filter { $0.1 != nil }
            .map { (item: (_key: String, _value: Any?)) -> URLQueryItem in
                URLQueryItem(name: item._key, value:"\(item._value!)")
            }
    }

    /**
     Get countries
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiCountryGet(completion: @escaping ((_ data: [Country]?,_ error: Error?) -> Void)) {
        apiCountryGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get countries
     - GET /api/Country
     - examples: [{contentType=application/json, example=[ {
  "code" : "aeiou",
  "isoCodes" : [ "aeiou" ],
  "name" : "aeiou",
  "id" : 123
} ]}]

     - returns: RequestBuilder<[Country]> 
     */
    open class func apiCountryGetWithRequestBuilder() -> RequestBuilder<[Country]> {
        let path = "/api/Country"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<[Country]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
