//
// ItemAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class ItemAPI: APIBase {

    public class func mapValuesToQueryItems(values: [String:Any?]) -> [URLQueryItem] {
        return values
            .filter { $0.1 != nil }
            .map { (item: (_key: String, _value: Any?)) -> URLQueryItem in
                URLQueryItem(name: item._key, value:"\(item._value!)")
            }
    }

    /**
     Close item
     
     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiItemByIdDelete(id: Int32, completion: @escaping ((_ error: Error?) -> Void)) {
        apiItemByIdDeleteWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Close item
     - DELETE /api/Item/{id}
     
     - parameter id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiItemByIdDeleteWithRequestBuilder(id: Int32) -> RequestBuilder<Void> {
        var path = "/api/Item/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get item by id
     
     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiItemByIdGet(id: Int32, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        apiItemByIdGetWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get item by id
     - GET /api/Item/{id}
     - examples: [{contentType=application/json, example="aeiou"}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<String> 
     */
    open class func apiItemByIdGetWithRequestBuilder(id: Int32) -> RequestBuilder<String> {
        var path = "/api/Item/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Update item
     
     - parameter id: (path)  
     - parameter value: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiItemByIdPut(id: Int32, value: String? = nil, completion: @escaping ((_ error: Error?) -> Void)) {
        apiItemByIdPutWithRequestBuilder(id: id, value: value).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Update item
     - PUT /api/Item/{id}
     
     - parameter id: (path)  
     - parameter value: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiItemByIdPutWithRequestBuilder(id: Int32, value: String? = nil) -> RequestBuilder<Void> {
        var path = "/api/Item/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = value?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)
        

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: convertedParameters, isBody: true)
    }

    /**
     Get all items for current user
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiItemGet(completion: @escaping ((_ data: [String]?,_ error: Error?) -> Void)) {
        apiItemGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get all items for current user
     - GET /api/Item
     - examples: [{contentType=application/json, example=[ "aeiou" ]}]

     - returns: RequestBuilder<[String]> 
     */
    open class func apiItemGetWithRequestBuilder() -> RequestBuilder<[String]> {
        let path = "/api/Item"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<[String]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Create item
     
     - parameter value: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiItemPost(value: String? = nil, completion: @escaping ((_ error: Error?) -> Void)) {
        apiItemPostWithRequestBuilder(value: value).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Create item
     - POST /api/Item
     
     - parameter value: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiItemPostWithRequestBuilder(value: String? = nil) -> RequestBuilder<Void> {
        let path = "/api/Item"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = value?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)
        

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: convertedParameters, isBody: true)
    }

}
