//
// SocialNetwork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SocialNetwork: JSONEncodable {
    public var socialType: String?
    public var socialUserId: String?
    public var isMaster: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["socialType"] = self.socialType
        nillableDictionary["socialUserId"] = self.socialUserId
        nillableDictionary["isMaster"] = self.isMaster
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
