//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class User: JSONEncodable {
    public var userId: Int32?
    public var socialNetworks: [SocialNetwork]?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var countryId: Int32?
    public var phoneNumber: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["userId"] = self.userId?.encodeToJSON()
        nillableDictionary["socialNetworks"] = self.socialNetworks?.encodeToJSON()
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["email"] = self.email
        nillableDictionary["countryId"] = self.countryId?.encodeToJSON()
        nillableDictionary["phoneNumber"] = self.phoneNumber
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
